apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-main-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ex-main-app
  template:
    metadata:
      labels:
        app: ex-main-app
    spec:
      containers:
        - image: exchangers/ex-main-app:0.0.2.RELEASE
          name: ex-main-app
      imagePullSecrets:
        - name: my-registry-secret
